# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - cmd: cmd.exe /D /C del femto-config.mk
        ignore_error: true
      - cmd: make config
      - cmd: make all
